sprint_7-solution-in-file-manager v1
Vagner-Viktor/java-kanban pull request #2
Opened 2024-02-27 16:50 UTC by Vagner-Viktor

Добавлена функциональность по техническому заданию 7

2024-02-28 05:48 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил пару комментоы

2024-02-28 05:48 UTC, ErkinKasymaliev commented on src/managers/FileBackedTaskManager.java
> +    public static String historyToString(HistoryManager manager) {
давайте этот метод и 3 ниже уберем в отдельный класс, например, FormatterUtil

2024-02-28 05:48 UTC, ErkinKasymaliev commented on test/managers/FileBackedTaskManagerTest.java
> +
давайте проверим правильность считывания файла, напишите тест, где сперва записываете объекты в файл, после создаете другой менеджер, который считывает файл и проверьте объекты 2х менеджеров -- правильно ли все причиталось (это доп задание)

2024-02-28 14:52 UTC, Vagner-Viktor commented on src/managers/FileBackedTaskManager.java
> +    public static String historyToString(HistoryManager manager) {
готово

2024-02-28 14:53 UTC, Vagner-Viktor commented on test/managers/FileBackedTaskManagerTest.java
> +
добавил тест checkingSavingAndLoadingTasksInDifferentManagers

2024-02-29 04:09 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-02-29 05:51 UTC, merged