Sprint 9 solution http-api
Vagner-Viktor/java-kanban pull request #4
Opened 2024-03-23 19:42 UTC by Vagner-Viktor

Доработка по ТЗ 9

2024-03-24 15:10 UTC, ErkinKasymaliev requested changes
привет, хорошая работа!
оставил комменты

2024-03-24 15:10 UTC, ErkinKasymaliev commented on test/http/HttpTaskServerTest.java
> +
а где тесты?

2024-03-24 15:10 UTC, ErkinKasymaliev commented on test/http/handler/EpicsHandlerTest.java
> +    public void setUp() {
наследуйте от HttpTaskServerTest, там у вас уже реализованы запуск и остановка сервера, не надо это прописывать в каждом handlerTest

2024-03-25 08:52 UTC, Vagner-Viktor commented on test/http/handler/EpicsHandlerTest.java
> +    public void setUp() {
добавил наследование

2024-03-25 08:52 UTC, Vagner-Viktor commented on test/http/HttpTaskServerTest.java
> +
написал тесты

2024-03-25 13:21 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-03-25 15:20 UTC, merged